Q1: 

Write a Python function that takes an array of integers as an argument and
returns a new array containing only the odd numbers in the original array.


In [1]:
# Function is odd_arr(x),which takes an array of integer as argument(x)
import numpy as np

def odd_arr(x): 
    x1=[]
    for i in x:
        if i%2==1:
            x1.append(i)
    y=np.array(x1)
    return y

#Example
x=np.array([78,63,95,45,88,48,62,31])
odd_arr(x)


array([63, 95, 45, 31])

Q2:

 Create a class called Dog with attributes name and breed. Add a method called bark that prints a message with the dog's name and a barking sound.


In [2]:
# Creating a class named Dog
class Dog:
    def __init__(self,name,breed):
        self.name=name
        self.breed=breed

# defining the bark function
def bark(Dog):
    bark_sound={'Bulldog':'Growl','German Shepherd':'Whimpers','Labrador':'Grunt','Husky':'Howl'}
    print('Hello friend!\nYour dog name is',Dog.name,'and its barking sound is',bark_sound[Dog.breed])


# Example
D1=Dog('Spike','Bulldog')
bark(D1)

Hello friend!
Your dog name is Spike and its barking sound is Growl


Q3. 

Write a Python program that creates a numpy array of 100 random integers
between 0 and 100, and prints any 2 measures of central tendency and 2 measures
of spread of the array.


In [3]:
import numpy as np
# Creating a random array
arr=np.random.randint(100,size=100)
print(arr)

# Measures of central tendency
print('\nThe mean of array is',np.sum(arr)/100)
print('The median of array is',np.median(arr))

# Measures of spread
print('\nThe standard deviation of array is',np.std(arr))
print('The range of array is',np.ptp(arr))

[81 20 53 83 83 98 52 42 46 97 89 29 27  6 34 37 16 80 85 79 98  4 55  9
 21 62 20 99 49 64 21 69 59 65 89 50 95 42 50 35 85 59  0 90 80 35 62 86
 20 30 98 96 39 98 49 69 93 52 80  3 45 62 23 37 94  4 90 98 32  9  5  7
 63 19 70 80 53 64  0 54 80 76 28 49 75  7 55 32 17 66 13 29 41 14 70 77
 40 56 43 75]

The mean of array is 52.69
The median of array is 53.0

The standard deviation of array is 29.273774953018957
The range of array is 99


Q1: Mandatory

Create a class which defines an __init__ function that initializes the class
attribute array. Define another function get_array which takes inputs for the
length of the array and inputs all the elements, and returns its corresponding sorted
Array.


In [ ]:
import numpy as np

# Creating a Class-
class array:
    def __init__(self,length,elements):
        self.length=length
        self.elements=elements


# Function get_array    
def get_array(array):
    return np.sort(np.array(array.elements))

# Enter length of array
l=int(input('Enter length of array '))

#Enter respective elements
try:
    e=[]
    for i in range(l):
        e.append(int(input(f'Enter element {i+1} [All elements should be of same type]')))
except ValueError:
    e=[]
    for i in range(l):
        e.append(input(f'Enter element {i+1} [All elements should be of same type]'))

arr=array(l,e)
print('Original:',np.array(arr.elements))
print('Sorted:',get_array(arr))



Q2: Mandatory

Write a single code for all parts of this question.

A. Create a 2D array of size 4*4 using list and perform the following
operations:
1. extract the diagonal elements from the array
2. Find the trace of the Matrix
3. Find the max and min element of each row in that matrix
(Hint: convert that 2D list to Numpy Array to make the problem simple)

B. Create another 2D numpy array with shape (4, 5) where each element of the
array is a random float between 0 and 1, inclusive, using numpy's uniform
distribution function. Print the resulting numpy array.

C. Multiply the numpy arrays created in Part A and Part B element-wise, and
print the resulting numpy array.



In [4]:
# Creating a 2D List
rows,columns=(4,4)
list=[[2,4,2,3],[9,3,1,2],[4,3,3,1],[0,9,7,1]]
# Creating 2D array A
import numpy as np
arr1=np.array(list)
print('Array A:')
print(arr1)
print('\nDiagonal elements are =',np.diag(arr1))   # 1. Extracting diagonal elements
print('Trace of matrix =',np.sum(np.diag(arr1))) # 2. Finding trace of matrix
print('Max element in each row respectively =',np.max(arr1,axis=1)) # Finding Maximum element 
print('Min element in each row respectively =',np.min(arr1,axis=1)) # Finding Minimum element

# array B
arr2=np.random.uniform(size=(4,5))
print('\nArray B:')
print(arr2)

# Part C
print('\nMultiplicative Array:')
print(np.dot(arr1,arr2))

Array A:
[[2 4 2 3]
 [9 3 1 2]
 [4 3 3 1]
 [0 9 7 1]]

Diagonal elements are = [2 3 3 1]
Trace of matrix = 9
Max element in each row respectively = [4 9 4 9]
Min element in each row respectively = [2 1 1 0]

Array B:
[[0.57509353 0.43778339 0.32524069 0.94234957 0.55714813]
 [0.3252144  0.5182211  0.55056072 0.43101398 0.82338006]
 [0.6691582  0.19197253 0.21145205 0.81305183 0.14900465]
 [0.41429348 0.91177822 0.63900224 0.63985151 0.45649945]]

Multiplicative Array:
[[ 5.0322415   6.06773088  5.1926351   7.15441324  6.07532415]
 [ 7.64923013  7.5102428   6.06830492 11.86694289  8.54647688]
 [ 5.6977854   4.79349266  4.22600333  8.1414472   5.60224608]
 [ 8.02533048  6.91957577  7.07421311 10.21034014  8.90995253]]
